import { useCallback, useState } from "react";

import PageHead from "@/components/PageHead";
import PublicLayout from "@/components/PublicLayout";
import { AIChatBox, type Message } from "@/components/AIChatBox";
import { SITE_URL } from "@/lib/siteConfig";
import {
  getNlwebWorkerUrl,
  streamNlwebChat,
  type NlwebMessage,
} from "@/lib/nlwebClient";
import { Sparkles } from "lucide-react";

const SYSTEM_PROMPT: Message = {
  role: "system",
  content:
    "You are the 1Commerce assistant, a concise and helpful AI for an " +
    "e-commerce SaaS platform. Answer questions about products, orders, " +
    "and the platform. If unsure, say so.",
};

const SUGGESTED_PROMPTS = [
  "What is UnifyOne?",
  "How do subscriptions work?",
  "Show me how to connect Shopify.",
  "Explain the multi-tenant model.",
];

/**
 * Public chat page that talks to the `1commerce-nlweb` Cloudflare Worker.
 *
 * Streams responses token-by-token via SSE so the user sees output as it is
 * generated by Workers AI.
 */
export default function NlwebChat() {
  const [messages, setMessages] = useState<Message[]>([SYSTEM_PROMPT]);
  const [isLoading, setIsLoading] = useState(false);

  const handleSend = useCallback(
    async (content: string) => {
      const next: Message[] = [...messages, { role: "user", content }];
      setMessages(next);
      setIsLoading(true);

      // Reserve a placeholder assistant message we'll fill in as chunks arrive.
      setMessages(prev => [...prev, { role: "assistant", content: "" }]);

      const wireMessages: NlwebMessage[] = next.map(m => ({
        role: m.role,
        content: m.content,
      }));

      try {
        await streamNlwebChat({ messages: wireMessages }, delta => {
          setMessages(prev => {
            const last = prev[prev.length - 1];
            if (!last || last.role !== "assistant") return prev;
            const updated = [...prev];
            updated[updated.length - 1] = {
              ...last,
              content: last.content + delta,
            };
            return updated;
          });
        });
      } catch (err) {
        const message =
          err instanceof Error ? err.message : "Unknown error";
        setMessages(prev => {
          const last = prev[prev.length - 1];
          const updated = [...prev];
          if (last && last.role === "assistant" && last.content === "") {
            updated[updated.length - 1] = {
              role: "assistant",
              content: `Sorry — the chat service is unavailable right now (${message}).`,
            };
          } else {
            updated.push({
              role: "assistant",
              content: `Sorry — the chat service is unavailable right now (${message}).`,
            });
          }
          return updated;
        });
      } finally {
        setIsLoading(false);
      }
    },
    [messages],
  );

  const workerUrl = getNlwebWorkerUrl();

  return (
    <PublicLayout>
      <PageHead
        title="AI Chat | UnifyOne"
        description="Chat with the 1Commerce AI assistant, powered by Cloudflare Workers AI."
        canonical={`${SITE_URL}/chat`}
      />

      <div className="min-h-screen pt-24 pb-16 px-4 sm:px-6 lg:px-8">
        <div className="max-w-4xl mx-auto">
          <header className="mb-8 text-center">
            <div className="inline-flex items-center gap-2 mb-3 px-3 py-1 rounded-full border border-[rgba(212,168,67,0.25)] text-[#D4A843] text-xs uppercase tracking-widest">
              <Sparkles className="w-3.5 h-3.5" />
              <span>1commerce-nlweb</span>
            </div>
            <h1 className="text-3xl sm:text-4xl font-semibold mb-3">
              AI Chat
            </h1>
            <p className="text-sm text-[rgba(240,232,208,0.7)] max-w-2xl mx-auto">
              Streaming responses from the{" "}
              <code className="text-[#D4A843]">1commerce-nlweb</code>{" "}
              Cloudflare Worker. Each message round-trips to{" "}
              <span className="text-[#D4A843]">{workerUrl}</span>.
            </p>
          </header>

          <div className="rounded-2xl border border-[rgba(212,168,67,0.18)] bg-[rgba(2,2,2,0.6)] backdrop-blur-md p-4 sm:p-6">
            <AIChatBox
              messages={messages}
              onSendMessage={handleSend}
              isLoading={isLoading}
              height="min(70vh, 640px)"
              emptyStateMessage="Ask me anything about UnifyOne."
              suggestedPrompts={SUGGESTED_PROMPTS}
              placeholder="Type a message and press Enter…"
            />
          </div>
        </div>
      </div>
    </PublicLayout>
  );
}
